export const FETCH_COLLECTIONS_PENDING = 'FETCH_COLLECTIONS_PENDING';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_ERROR = 'FETCH_COLLECTIONS_ERROR';
